### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by jackdellis** [matasarei/tryonface#1]
Would love to have a play around with this but couldn't get it to load in Chrome. I'm running Chrome 72. I was using a https connection to view the demo. 

Regards, Jack

**Comment by martinhayon** [comment]
Hi how are you i'm testing your project on my localhost and it works fine. But on safari or chrome on iPhone it's not working, have you tried? have you some feedback about this behavior?
Thanks
Regards Martin

**Comment by matasarei** [comment]
Hello Martin. Just checked it on the latest Chrome (90.0.4430.212) - works as expected. If you going to use this demo for your project I would recommend to update all dependencies and refactor the code. Also, HTTPS connection is mandatory to use camera.
